### ISSUE TITLE
Day :- 2  Add Product and Cart and Order Functionality

### ISSUE THREAD

**Issue by rishunayak** [rishunayak/purplle#2]
- [x] Add Product Data to Backend
- [x] Cart API for Get Data
- [x] Cart API for Post Data
- [x] Cart API for Patch Data
- [x] Cart API for Delete Data
- [x] OrderHistrory API to get Data 
- [x]  OrderHistrory API to Post Data

**Comment by naszifnaaz** [comment]
Done #16
