### ISSUE TITLE
Day 2: Beaury Profile and User WishList

### ISSUE THREAD

**Issue by sanjayrathva091** [rishunayak/purplle#8]
- [x] Describe your complexion.(Choose any one)
- [x] How would you classify your hair?(Choose any one)
- [x] Describe your hair.(Choose all that apply)
- [x] Which hair issues would you like to conquer?(Choose all that apply)
- [x] Your Scalp Concern(Choose all that apply)
- [x] How would you classify your skin?(Choose any one)
- [x] Which skin issues would you like to conquer?(Choose all that apply)
- [x] Your Style Preference(Choose any one)
- [x] Find items across your wish list
- [x] Display wish list products
- [x] Make it responsive design

**Comment by naszifnaaz** [comment]
Done #27
